In [1]:
print("a")

a


Merhaba
_italic_
**kalın**

In [2]:
"a"

'a'

In [7]:
#Merhaba

# Neden NumPy ?

## Bu bir Alt Başlıktır 

In [10]:
a = [1,2,3,4]
b = [2,3,4,5]

In [11]:
ab = []
for i in range (0, len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

# Arrays

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [9]:
np.array([3.14,4,2,13], dtype = int)

array([ 3,  4,  2, 13])

## Sifirdan Array Olusturma

In [10]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full ((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [14]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4,(3,4))

array([[10.12152171, 11.78847639, 11.68303487,  7.44858564],
       [11.96397543, 11.68109395,  3.78014264, 12.10317982],
       [12.55240317,  4.19608658, 10.51794304, 12.83805177]])

In [18]:
np.random.randint(0,10,(3,3))

array([[5, 8, 9],
       [3, 6, 5],
       [4, 2, 6]])

## Ozellikleri

* ndim: boyut sayısı
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [19]:
np.random.randint(10, size = 10)

array([8, 6, 9, 4, 3, 9, 6, 5, 3, 4])

In [20]:
a = np.random.randint(10, size = 10)

In [21]:
a.ndim

1

In [22]:
a.shape

(10,)

In [23]:
a.size

10

In [24]:
a.dtype

dtype('int32')

In [31]:
b = np.random.randint(10, size = (3,5))

In [32]:
b

array([[9, 2, 4, 1, 5],
       [3, 7, 9, 9, 6],
       [7, 6, 1, 3, 2]])

In [33]:
b.ndim

2

In [34]:
b.shape

(3, 5)

In [35]:
b.size

15

In [36]:
b.dtype

dtype('int32')

# Yeniden Sekillendirme (Reshaping)

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.ndim

1

In [46]:
b = a.reshape((1,9))
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
b.ndim

2

# Birlestirme (Concantenation)

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [48]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [49]:
z = np.array([7,8,9])

In [50]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## İki Boyutlu

In [52]:
a = np.array([[1,2,3],[4,5,6]])

In [53]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayirma (Splitting)

In [65]:
x = np.array([1,2,3,99,99,3,2,1,2,3])

In [64]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1, 2, 3])]

In [68]:
a,b,c = np.split(x, [3,5])
print(a,b,c)

[1 2 3] [99 99] [3 2 1 2 3]


### Iki Boyutlu Ayirma

In [69]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [80]:
ust, alt = np.vsplit(m, [2])
print(f"Ust satir: {ust}\n Alt satir: {alt}")

Ust satir: [[0 1 2 3]
 [4 5 6 7]]
 Alt satir: [[ 8  9 10 11]
 [12 13 14 15]]


In [77]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
sag, sol = np.hsplit(m, [2])
print(f"Sag taraf: {sag} \nSol taraf: {sol}")

Sag taraf: [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
Sol taraf: [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Siralama (Sorting)

In [84]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [85]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [86]:
v.sort()

In [87]:
v

array([1, 2, 3, 4, 5])

### Iki Boyutlu Siralama

In [89]:
m = np.random.normal(20,5, (3,3))
m

array([[17.80126271,  9.34673989, 26.56067495],
       [26.54916584, 24.62917509, 22.46555424],
       [16.3206721 , 25.58867617, 22.05405482]])

In [93]:
np.sort(m, axis = 1) #Sagdan sola kucukten buyuge siralama

array([[ 9.34673989, 17.80126271, 26.56067495],
       [22.46555424, 24.62917509, 26.54916584],
       [16.3206721 , 22.05405482, 25.58867617]])

In [92]:
np.sort(m, axis = 0) #Yukaridan asagi kucukten buyuge siralama

array([[16.3206721 ,  9.34673989, 22.05405482],
       [17.80126271, 24.62917509, 22.46555424],
       [26.54916584, 25.58867617, 26.56067495]])

# Eleman islemleri

## Index ile Elemanlara Erismek

In [4]:
a = np.random.randint(10, size = (3,5))
a

array([[1, 1, 3, 9, 4],
       [2, 0, 9, 1, 7],
       [0, 9, 7, 0, 4]])

In [9]:
a[0,0] = 55
a[0,0]

55

In [10]:
a[2,3]

0

In [12]:
a[2,2] = 3.1 # sonradan eklenenler ana tipi bozmaz, olustururken ondalikli yapsaydik da int ekledigimizde de floata cevirirdi
a

array([[55,  1,  3,  9,  4],
       [ 2,  0,  9,  1,  7],
       [ 0,  9,  3,  0,  4]])

## Array Alt Kume İslemleri

In [14]:
x = np.arange(20,30)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
x[0:3]

array([20, 21, 22])

In [16]:
x[:3]

array([20, 21, 22])

In [17]:
x[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [18]:
x[1::2]

array([21, 23, 25, 27, 29])

### İki Boyutlu Slice islemleri

In [37]:
m = np.random.randint(10, size = (5,5))
m

array([[4, 1, 6, 6, 5],
       [3, 8, 9, 2, 6],
       [4, 0, 3, 4, 8],
       [5, 4, 4, 8, 4],
       [2, 5, 8, 9, 2]])

In [22]:
m[:,0] # butun satirlar seciliyken sadece ilk indexli sutunlara erisim sagladik

array([1, 1, 9, 3, 2])

In [24]:
m[:,1]

array([2, 3, 3, 6, 2])

In [26]:
m[0,:] # butun sutunlar seciliyken sadece ilk indexli satirlara erisim sagladik

array([1, 2, 1, 8, 7])

In [27]:
m[0]

array([1, 2, 1, 8, 7])

In [28]:
m[0:2, 0:3]

array([[1, 2, 1],
       [1, 3, 6]])

In [29]:
m[0:2, 0:4]

array([[1, 2, 1, 8],
       [1, 3, 6, 0]])

In [31]:
m[::,:2] # ilk iki sutunu getirmis olduk

array([[1, 2],
       [1, 3],
       [9, 3],
       [3, 6],
       [2, 2]])

In [33]:
m[:,0:2]

array([[1, 2],
       [1, 3],
       [9, 3],
       [3, 6],
       [2, 2]])

In [34]:
m[:,:2]

array([[1, 2],
       [1, 3],
       [9, 3],
       [3, 6],
       [2, 2]])

In [35]:
m[1:3, 0:2]

array([[1, 3],
       [9, 3]])

### Alt Kume Uzerinde Islem Yapmak

In [5]:
a = np.random.randint(10, size = (5,5))
a

array([[3, 6, 2, 2, 0],
       [7, 1, 9, 0, 3],
       [1, 3, 2, 3, 9],
       [2, 6, 0, 0, 3],
       [7, 6, 3, 6, 3]])

In [6]:
alt_a = a[0:3, 0:2]
alt_a

array([[3, 6],
       [7, 1],
       [1, 3]])

In [7]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [8]:
alt_a

array([[99999,     6],
       [    7,   888],
       [    1,     3]])

In [9]:
a

array([[99999,     6,     2,     2,     0],
       [    7,   888,     9,     0,     3],
       [    1,     3,     2,     3,     9],
       [    2,     6,     0,     0,     3],
       [    7,     6,     3,     6,     3]])

In [10]:
m = np.random.randint(10, size = (5,5))
m

array([[5, 4, 4, 3, 7],
       [0, 4, 4, 4, 0],
       [8, 4, 8, 9, 4],
       [1, 8, 0, 5, 0],
       [0, 5, 5, 7, 9]])

In [15]:
alt_m = m[0:3, 0:2].copy() # bu copy metodu sayesinde ne yaparsak yapalim hicbir kalici degisiklik olmaz, boylece alt kumelerle calisabiliriz
alt_m*3

array([[15, 12],
       [ 0, 12],
       [24, 12]])

In [14]:
m

array([[5, 4, 4, 3, 7],
       [0, 4, 4, 4, 0],
       [8, 4, 8, 9, 4],
       [1, 8, 0, 5, 0],
       [0, 5, 5, 7, 9]])

### Fancy Index ile Elemanlara Erismek

In [16]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [19]:
al_getir = [1,3,5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [20]:
v[al_getir]

array([ 3,  9, 15])

#### Iki Boyutta Fancy

In [22]:
n = np.arange(9).reshape((3,3))
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [25]:
n[satir, sutun]

array([1, 5])

In [26]:
# basit index ile fancy index

In [28]:
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
n[0, [1,2]]

array([1, 2])

In [32]:
#slice ile fancy

In [31]:
n[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Kosullu Eleman Islemleri

In [33]:
y = np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

In [36]:
y>5

array([False, False, False, False, False])

In [37]:
y<3

array([ True,  True, False, False, False])

In [38]:
y[y>1]

array([2, 3, 4, 5])

In [39]:
y*3

array([ 3,  6,  9, 12, 15])

In [40]:
y/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [41]:
y*10/12

array([0.83333333, 1.66666667, 2.5       , 3.33333333, 4.16666667])

In [42]:
y**2

array([ 1,  4,  9, 16, 25])

In [43]:
y**3

array([  1,   8,  27,  64, 125], dtype=int32)

## Math Operations

In [44]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
a -1 

array([0, 1, 2, 3, 4])

In [46]:
# Butun bu islemlere "ufunc" denilir cunku Numpy'in icerisindeki fonksiyonlar cagirilarak otomatik olarak yapilir

In [48]:
np.absolute(-5)

5

In [52]:
arr = np.array([-46])

# Use numpy.absolute() to get the absolute value
arr2 = np.absolute(arr)
arr2

array([46])

In [53]:
np.sin(360)

0.9589157234143065

In [54]:
np.cos(180)

-0.5984600690578581

In [55]:
np.cos(360)

-0.2836910914865273

In [57]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [58]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [59]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [60]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\PC\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\pc\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x

In [62]:
#ilgili dilin ya da kutuphanenin adini girerek ve "cheat sheet" yazarak butun dokumanlara ulasabiliriz

## Numpy ile Iki Bilinmeyenli Denklem Cozumu

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [65]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])
a

array([[5, 1],
       [1, 3]])

In [66]:
b

array([12, 10])

In [67]:
x = np.linalg.solve(a,  b)
x

array([1.85714286, 2.71428571])

In [68]:
# Veri Manipulasyonu 101 Bitti

In [69]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
import numpy as np
np.random.randint(10, size = (1,3,2))

array([[[1, 2],
        [4, 7],
        [0, 9]]])

In [77]:
import numpy as np
np.random.randint(10, size = (2,3,2))

array([[[5, 7],
        [5, 5],
        [7, 8]],

       [[5, 3],
        [8, 6],
        [2, 7]]])

In [78]:
import numpy as np
np.random.randint(10, size = (3,2,2))

array([[[5, 1],
        [7, 0]],

       [[8, 4],
        [5, 3]],

       [[6, 0],
        [1, 5]]])

In [2]:
import numpy as np
np.random.randint(10, size = (3,3,2))

array([[[5, 7],
        [1, 3],
        [9, 2]],

       [[0, 6],
        [9, 8],
        [5, 7]],

       [[1, 6],
        [1, 5],
        [8, 4]]])

In [80]:
import numpy as np
np.random.randint(10, size = (3,3,1))

array([[[9],
        [1],
        [5]],

       [[7],
        [6],
        [4]],

       [[9],
        [7],
        [5]]])

In [81]:
v = np.array([2, 1, 4, 3, 5])

np.sort(v)

array([1, 2, 3, 4, 5])

In [82]:
m =np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])

m[0, [1,2]]

array([1, 2])

# Veri Manipülasyonu 201

## Pandas Giris

In [2]:
import pandas as pd

In [4]:
pd.Series([10,22,3,4,5])

0    10
1    22
2     3
3     4
4     5
dtype: int64

In [15]:
seri = pd.Series([10,22,3,4,5])
type(seri)

pandas.core.series.Series

In [16]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [17]:
seri.dtype

dtype('int64')

In [18]:
seri.size

5

In [19]:
seri.ndim

1

In [20]:
seri.values

array([10, 22,  3,  4,  5], dtype=int64)

In [21]:
seri.head

<bound method NDFrame.head of 0    10
1    22
2     3
3     4
4     5
dtype: int64>

In [22]:
seri.tail

<bound method NDFrame.tail of 0    10
1    22
2     3
3     4
4     5
dtype: int64>

In [23]:
# index isimlendirmesi

In [25]:
pd.Series([100,24,353,45,5])

0    100
1     24
2    353
3     45
4      5
dtype: int64

In [27]:
pd.Series([100,24,353,45,5], index = [1,3,5,7,9])

1    100
3     24
5    353
7     45
9      5
dtype: int64

In [29]:
seri = pd.Series([100,24,353,45,5], index = ["a","b","c","d","e"])

In [30]:
seri["a"]

100

In [31]:
seri["a":"c"]

a    100
b     24
c    353
dtype: int64

In [32]:
# sozluk uzerinden liste olusturmak

In [40]:
sozluk = pd.Series({"reg":10, "log": 24, "cart":"a"}) # buraya "a" koydugumuz icin turu object oldu

In [41]:
sozluk

reg     10
log     24
cart     a
dtype: object

In [38]:
# iki seriyi birlestirerek seri olusturma

In [42]:
pd.concat([seri,sozluk])

a       100
b        24
c       353
d        45
e         5
reg      10
log      24
cart      a
dtype: object

## Eleman Islemleri

In [44]:
a = np.array([11,22,38,47,53])
seri = pd.Series(a)
seri

0    11
1    22
2    38
3    47
4    53
dtype: int32

In [45]:
sozluk.index

Index(['reg', 'log', 'cart'], dtype='object')

In [46]:
sozluk.keys

<bound method Series.keys of reg     10
log     24
cart     a
dtype: object>

In [48]:
list(seri.items())

[(0, 11), (1, 22), (2, 38), (3, 47), (4, 53)]

In [49]:
list(sozluk.items())

[('reg', 10), ('log', 24), ('cart', 'a')]

In [50]:
sozluk.values

array([10, 24, 'a'], dtype=object)

In [51]:
seri.values

array([11, 22, 38, 47, 53])

In [52]:
# eleman sorgulama

In [53]:
"reg" in sozluk

True

In [54]:
"red" in seri

False

In [55]:
"reg" in seri

False

In [56]:
sozluk["reg"]

10

In [57]:
# fancy eleman

In [59]:
sozluk[["log","reg"]]

log    24
reg    10
dtype: object

## Pandas Dataframe Olusturma

In [3]:
l = [1,2,39,67,90]
l

[1, 2, 39, 67, 90]

In [4]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [5]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [8]:
#df isimlendirme

In [10]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [14]:
df.columns = ("deg1","deg2","deg3")
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [17]:
df.shape

(3, 3)

In [18]:
df.ndim

2

In [19]:
df.size

9

In [20]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
type(df.values)

numpy.ndarray

In [22]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [23]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [24]:
a = np.array([1,2,3,4,5])

In [25]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

## Eleman Islemleri

In [26]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [27]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}
sozluk

{'var1': array([0, 7, 8, 7, 5]),
 'var2': array([1, 7, 4, 6, 4]),
 'var3': array([7, 8, 4, 3, 1])}

In [29]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     0     1     7
1     7     7     8
2     8     4     4
3     7     6     3
4     5     4     1

In [30]:
df[0:1]

var1  var2  var3
0     0     1     7

In [31]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     0     1     7
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [33]:
df["c":"e"]

var1  var2  var3
c     8     4     4
d     7     6     3
e     5     4     1

In [34]:
# silme

In [35]:
df.drop("a", axis = 0)

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [36]:
df

var1  var2  var3
a     0     1     7
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [37]:
df.drop("a", axis = 0, inplace = True)
df

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [38]:
#fancy

In [39]:
l = ["c","e"]

In [40]:
df.drop(l, axis=0)

var1  var2  var3
b     7     7     8
d     7     6     3

In [41]:
# degiskenler icin

In [42]:
df

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [43]:
"var1" in df

True

In [44]:
l = ["var1","var4","var2"]

In [45]:
for i in l:
    print(i in df)

True
False
True


In [46]:
df

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [47]:
df["var4"] = df["var1"] * df["var2"]
df

var1  var2  var3  var4
b     7     7     8    49
c     8     4     4    32
d     7     6     3    42
e     5     4     1    20

In [48]:
# degisken silmek

In [49]:
df.drop("var4", axis = 1)

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [50]:
df

var1  var2  var3  var4
b     7     7     8    49
c     8     4     4    32
d     7     6     3    42
e     5     4     1    20

In [53]:
df.drop("var4", axis = 1, inplace = True)

In [54]:
df

var1  var2  var3
b     7     7     8
c     8     4     4
d     7     6     3
e     5     4     1

In [57]:
l = ["var1","var2"]

In [58]:
df.drop(l, axis = 1)

var3
b     8
c     4
d     3
e     1

## Gozlem ve Degisken Secimi: loc & iloc

In [2]:
import pandas as pd
import numpy as np

In [6]:
m = np.random.randint( 1, 30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    21     4    13
1    28     9    24
2     3    14    28
3    13    25    28
4    10    13     9
5    27    16    13
6    12     5    16
7    24    29    26
8    25    29    23
9    20    16    10

In [7]:
#loc: tanimladigi sekli ile secim yapmak icin kullanilir

In [8]:
df.loc[0:3]

var1  var2  var3
0    21     4    13
1    28     9    24
2     3    14    28
3    13    25    28

In [9]:
df.loc[0:2]

var1  var2  var3
0    21     4    13
1    28     9    24
2     3    14    28

In [10]:
#iloc: alisik oldugumuz indeksleme mantigi ile secim yapar.

In [11]:
df.iloc[0:3]

var1  var2  var3
0    21     4    13
1    28     9    24
2     3    14    28

In [12]:
df[0:3]

var1  var2  var3
0    21     4    13
1    28     9    24
2     3    14    28

In [13]:
df.loc[0:3, "var3"]

0    13
1    24
2    28
3    28
Name: var3, dtype: int32

In [15]:
df.iloc[0:3, "var3"] # hata verdi ve iloc'un kullanilamayacagini, boyle secim durumlarinda locun kullanilmasi gerektigini gosterir

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [16]:
df.iloc[0:3]["var3"]

0    13
1    24
2    28
Name: var3, dtype: int32

### Kosullu Eleman islemleri

In [17]:
n = np.random.randint( 1, 30, size = (10,3))
df = pd.DataFrame(n, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    29     4    10
1    10    29    17
2    21    12    25
3    26     5    16
4    10     9    25
5     7    15     5
6    12    27     2
7    11    28    16
8     1     4    11
9    21    11     9

In [21]:
df[df.var1 > 10]

var1  var2  var3
0    29     4    10
2    21    12    25
3    26     5    16
6    12    27     2
7    11    28    16
9    21    11     9

In [22]:
df[df.var1 > 10]["var2"]

0     4
2    12
3     5
6    27
7    28
9    11
Name: var2, dtype: int32

In [23]:
df[(df.var1 > 10) & (df.var3 < 5)]

var1  var2  var3
6    12    27     2

In [24]:
df[(df.var1 > 10), ["var1","var2"]] # hata aliriz lakin

InvalidIndexError: (0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8    False
9     True
Name: var1, dtype: bool, ['var1', 'var2'])

In [25]:
df.loc[(df.var1 > 10), ["var1","var2"]] # dfnin basina ".loc" ekledigimizde sorun cozulur ve coklu secim yapabiliriz

var1  var2
0    29     4
2    21    12
3    26     5
6    12    27
7    11    28
9    21    11

In [26]:
df[(df.var1 > 10)] [["var1","var2"]] # ya da fancy olarak bunu gosterip alabiliriz

var1  var2
0    29     4
2    21    12
3    26     5
6    12    27
7    11    28
9    21    11

## Birlestirme (Join) Islemleri

In [6]:
m = np.random.randint( 1, 30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0     8    14     4
1    17    22    28
2     6    17    29
3    10     2    21
4    22     2    24

In [7]:
df2 = df1 +99
df2

var1  var2  var3
0   107   113   103
1   116   121   127
2   105   116   128
3   109   101   120
4   121   101   123

In [12]:
pd.concat([df1, df2])

var1  var2  var3
0     8    14     4
1    17    22    28
2     6    17    29
3    10     2    21
4    22     2    24
0   107   113   103
1   116   121   127
2   105   116   128
3   109   101   120
4   121   101   123

In [15]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'col

In [17]:
pd.concat([df1, df2], ignore_index = True)

var1  var2  var3
0     8    14     4
1    17    22    28
2     6    17    29
3    10     2    21
4    22     2    24
5   107   113   103
6   116   121   127
7   105   116   128
8   109   101   120
9   121   101   123

In [18]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [19]:
df2.columns = ["var1","var2","deg1"]
df2.columns

Index(['var1', 'var2', 'deg1'], dtype='object')

In [20]:
pd.concat([df1, df2])

var1  var2  var3   deg1
0     8    14   4.0    NaN
1    17    22  28.0    NaN
2     6    17  29.0    NaN
3    10     2  21.0    NaN
4    22     2  24.0    NaN
0   107   113   NaN  103.0
1   116   121   NaN  127.0
2   105   116   NaN  128.0
3   109   101   NaN  120.0
4   121   101   NaN  123.0

In [21]:
pd.concat([df1, df2], join = "inner") # eger yukaridaki gibi bir concat islemi yaparsak hata alabiliriz ve karmasa cikabilir, bu yuzden join metodunu kullaniyoruz

var1  var2
0     8    14
1    17    22
2     6    17
3    10     2
4    22     2
0   107   113
1   116   121
2   105   116
3   109   101
4   121   101

In [23]:
pd.concat([df1, df2], join_axes = [df1.columns]) # bu metod kaldirilmis sanirim ve kullanilamiyor :(

TypeError: concat() got an unexpected keyword argument 'join_axes'

## Ileri Birlestirme Islemleri

In [2]:
# birebir birlestirme

In [3]:
df1 = pd.DataFrame({"calisanlar": ["Ali", "Veli", "Ayse", "Fatma"], "grup": ["Muhasebe", "Muhendislik", "Muhendislik","IK"]})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           IK

In [4]:
df2 = pd.DataFrame({"calisanlar": ["Ayse", "Ali", "Veli", "Fatma"], "ilk_giris": [2010, 2009, 2014, 2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [5]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [6]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [7]:
#coktan teke

In [8]:
df3 = pd.merge(df1, df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           IK       2019

In [9]:
df4 = pd.DataFrame({"grup": ["Muhasebe", "Muhendislik", "IK"], "mudur": ["Caner", "Mustafa", "Berkcan"]})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           IK  Berkcan

In [10]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           IK       2019  Berkcan

In [11]:
# coktan coka

In [12]:
df5 = pd.DataFrame({"grup": ["Muhasebe", "Muhasebe", "Muhendislik", "Muhendislik", "IK", "IK"], "yetenekler": ["matematik", "excel", "kodlama", "linux", "excel", "yonetim"]})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           IK      excel
5           IK    yonetim

In [13]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           IK      excel
7      Fatma           IK    yonetim

## Gruplama ve Toplulastirma (Grouping & Aggregation )

Basit toplulastirma fonksiyonlari:

count()
first()
last()
mean()
median()
min()
max()
std()
var()
sum()

In [3]:
import seaborn as sns

In [15]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [16]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [18]:
df.shape

(1035, 6)

In [19]:
df.min()

method            Astrometry
number                     1
orbital_period      0.090706
mass                  0.0036
distance                1.35
year                    1989
dtype: object

In [25]:
df["mass"].mean()

2.6381605847953216

In [24]:
df["mass"].count()

513

In [26]:
df["mass"].min()

0.0036

In [27]:
df["mass"].max()

25.0

In [28]:
df["mass"].sum()

1353.37638

In [29]:
df["mass"].std()

3.8186166509616046

In [30]:
df["mass"].var()

14.58183312700122

In [31]:
df.describe() # butun hepsini elle yazmak yerine toplandigi kisayolu cagirdik

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [32]:
df.describe().T # bunun ters grafigini cagirdik

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [33]:
df.dropna().describe().T #dropna fonksiyonu ile eksik olan verileri silerek daha duzenli hale getirebiliriz

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

## Gruplama Islemleri

In [5]:
df = pd.DataFrame({"gruplar": ["A", "B", "C", "A", "B", "C"], "veri": [10,11,52,23,43,55]}, columns = ["gruplar", "veri"])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [6]:
df.groupby("gruplar")

In [7]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [8]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [9]:
df.groupby("gruplar").max()

veri
gruplar      
A          23
B          43
C          55

In [10]:
df.groupby("gruplar").min()

veri
gruplar      
A          10
B          11
C          52

In [11]:
df = sns.load_dataset("planets")
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [12]:
df.groupby("method")

In [15]:
df.groupby("method")["orbital_period"]

In [14]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [16]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [17]:
df.groupby("method")["orbital_period"].sum()

method
Astrometry                       1.262360e+03
Eclipse Timing Variations        4.276480e+04
Imaging                          1.418973e+06
Microlensing                     2.207500e+04
Orbital Brightness Modulation    2.127920e+00
Pulsar Timing                    3.671511e+04
Pulsation Timing Variations      1.170000e+03
Radial Velocity                  4.553151e+05
Transit                          8.377523e+03
Transit Timing Variations        2.393505e+02
Name: orbital_period, dtype: float64

In [18]:
df.groupby("method")["orbital_period"].std()

method
Astrometry                          544.217663
Eclipse Timing Variations          2499.130945
Imaging                          213978.177277
Microlensing                       1113.166333
Orbital Brightness Modulation         0.725493
Pulsar Timing                     16313.265573
Pulsation Timing Variations                NaN
Radial Velocity                    1454.926210
Transit                              46.185893
Transit Timing Variations            71.599884
Name: orbital_period, dtype: float64

In [19]:
df.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

# Ileri Toplulastirma Islemleri

## Aggregate

In [20]:
import pandas as pd
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},
                 columns = ["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [21]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [24]:
df.groupby("gruplar").aggregate(["min", np.median, max ]) #pandasin icindeki fonksiyonlari kullanirken tirnak koymasak da olur ama tirnakla da olur, np.median tirnakla calismaz ama pandas fonksiyonlari calisir

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [25]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

## Filter

In [27]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},
                 columns = ["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [28]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [30]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [31]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

## Transform

In [32]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"],
                  "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},
                 columns = ["gruplar", "degisken1", "degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [33]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [35]:
df_a = df.iloc[:,1:3]

In [39]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2 gruplar
0  -0.687871  -0.738461     NaN
1  -0.299074  -0.263736     NaN
2   0.000000  -0.015514     NaN
3  -0.328982  -0.235811     NaN
4  -0.657963  -0.704331     NaN
5   1.973890   1.957853     NaN

## Apply

In [41]:
df = pd.DataFrame({
                  "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},
                 columns = ["degisken1", "degisken2"])
df

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [42]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [43]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

## Pivot Tablolar

In [44]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [45]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [47]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [48]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [49]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

survived
sex    class           
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [50]:
# pivot ile table

In [51]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [52]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [53]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

In [54]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

## Dis Kaynakli Veri Okuma

In [4]:
import pandas as pd

In [10]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols=None,
    squeeze: 'bool | None' = None,
    prefix: 'str | lib.NoDefault' = <no_default>,
    mangle_dupe_cols: 'bool' = True,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace: 'bool' = False,
    skiprows=None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    skip_blank_lines: 'bool' = True,
    parse_dates=None,
    infer

In [6]:
# csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [9]:
# txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [12]:
# excel okuma
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [13]:
df = pd.read_excel("reading_data/ornekx.xlsx")
type(df)

pandas.core.frame.DataFrame

In [15]:
df.columns = ("A", "B", "C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [16]:
# sınav

In [17]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])

In [18]:
df

var1  var2  var3
0     4     2     1
1    19     8    29
2     9    14     2
3     3    26    12
4    10    13    29
5     2    27     2
6     7     3    12
7    20    11    11
8     6    13    25
9     9     4    27

In [21]:
df[(df.var1 > 15)][[ "var1","var2"]]

var1  var2
1    19     8
7    20    11

In [23]:
df.describe().T

count  mean        std  min   25%   50%    75%   max
var1   10.0   8.9   6.190495  2.0  4.50   8.0   9.75  20.0
var2   10.0  12.1   8.748968  2.0  5.00  12.0  13.75  27.0
var3   10.0  15.0  11.566234  1.0  4.25  12.0  26.50  29.0

In [24]:
seri = pd.Series([121,200,150,99])

seri.values

array([121, 200, 150,  99], dtype=int64)